# Generated by Django 3.2.6 on 2021-08-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600, unique=True, verbose_name='URL')),
                ('short_url', models.URLField(max_length=300, unique=True, verbose_name='Short URL')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessions.session', verbose_name='Сессия')),
            ],
        ),
    ]
