# Generated by Django 3.2.6 on 2021-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0002_auto_20210822_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplink',
            name='link',
            field=models.URLField(max_length=600, verbose_name='LINK'),
        ),
        migrations.AlterUniqueTogether(
            name='maplink',
            unique_together={('session', 'link')},
        ),
    ]
