# Generated by Django 3.2.6 on 2021-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210823_0906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maplink',
            unique_together=set(),
        ),
    ]
